require'lspconfig'.bashls.setup{}
require'lspconfig'.clangd.setup{}
require'lspconfig'.cmake.setup{}
require'lspconfig'.dockerls.setup{}
require'lspconfig'.html.setup{}
require'lspconfig'.phpactor.setup{}
require'lspconfig'.pyright.setup{}
require'lspconfig'.sqls.setup{}
require'lspconfig'.texlab.setup{}
require'lspconfig'.tsserver.setup{}
require'lspconfig'.yamlls.setup{}
